//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_GIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public string Vin { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public int Weight { get; set; }
        public string DriveType { get; set; }
        public int IdColor { get; set; }
        public int IdEngine { get; set; }
        public int IdDriver { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Engine Engine { get; set; }
    }
}
