//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_GIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class HystoryStatus
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int IdLicence { get; set; }
        public int IdStatusLicence { get; set; }
    
        public virtual Licence Licence { get; set; }
        public virtual StatusLicence StatusLicence { get; set; }
    }
}
