//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_GIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licence()
        {
            this.HystoryStatus = new HashSet<HystoryStatus>();
        }
    
        public int Id { get; set; }
        public string LicenceDate { get; set; }
        public string ExpireDate { get; set; }
        public string Categories { get; set; }
        public int LicenceSeries { get; set; }
        public int LicenceNumber { get; set; }
        public int IdDriver { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HystoryStatus> HystoryStatus { get; set; }
        public virtual StatusLicence StatusLicence { get; set; }
    }
}
