//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_GIBDD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GIBDDEntities : DbContext
    {
        public GIBDDEntities()
            : base("name=GIBDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Engine> Engine { get; set; }
        public virtual DbSet<HystoryStatus> HystoryStatus { get; set; }
        public virtual DbSet<Licence> Licence { get; set; }
        public virtual DbSet<RegionCode> RegionCode { get; set; }
        public virtual DbSet<StatusLicence> StatusLicence { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
