//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_GIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCode
    {
        public int Id { get; set; }
        public string NameEng { get; set; }
        public string NameRu { get; set; }
        public Nullable<int> SubjectCode { get; set; }
        public string Code { get; set; }
        public Nullable<int> OkatoCode { get; set; }
        public string Gost { get; set; }
    }
}
